spring:
  datasource:
    url: jdbc:mysql://192.168.8.116:3690/study?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: hr
    password: 123123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    appname: Product
server:
  port: 8002
