spring:
  datasource:
    url: jdbc:mysql://garfieldsen.mysql.rds.aliyuncs.com:3690/product?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: senli
    password: lisen88se*

  application:
    name: Product

eureka:
  client:
    service-url:
      defaultZone: http://192.168.8.56:8001/eureka
  instance:
    appname: Product


server:
  port: 8002
